[Definition]
# Ta filter preskoči datum, poišče "[WARNING]", in nato prebere IP naslov
failregex = ^.* - .* - \[WARNING\] - .*: ZAVRNJENA_PRIJAVA IP: <HOST> Uporabnik: .*$
            ^.* - .* - \[WARNING\] - .*: ZAHTEVA_ZA_GESLO IP: <HOST> Email: .*$

ignoreregex =
